name: Trigger Jenkins Job on Push

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl --silent --show-error --fail \
          "http://46.101.131.225:8080/job/ToDo%20test%20and%20deploy/build?token=SecureToken123400943651495734531834"
